info:
  version: @pom.version@
logging:
  file: logs/spring-boot-workshop.log

server:
    port: 8585

endpoints:
   health:
     sensitive: false
   metrics:
     enabled: true

metrics:
     jmx.enabled: true
